spring.application.name=gallerist
spring.datasource.url=jdbc:postgresql://localhost:5432/spring-projects-postgres
spring.jpa.properties.hibernate.default_schema=gallery-management
spring.datasource.username=postgres
spring.datasource.password=111

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


jwt.expiration=7200000
jwt.secret=2uzxagvUacaYcV4Mxnca3M4/Y2jrQOVXJOmEphetq3E=
jwt.refresh.expiration=604800000